version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Darian --lastname Wong --role Admin --email thedarianwong@gmail.com
      "
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./airflow:/opt/airflow
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: scheduler
    volumes:
      - ./airflow:/opt/airflow
    env_file:
      - .env
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres-db-volume: